### ISSUE TITLE
disclose forvo api request script?

### ISSUE THREAD

**Issue by pcuinty** [polo-mint-driller/plad_anki#1]
hey there,

It would be great, if you considered disclosing your script which you used to download audio files from forvo? I'd like to use it as a starting point for downloading audio files for my verb conjugation deck.

**Comment by polo-mint-driller** [comment]
Hi,

Sorry the response took so long. The API is behind a paywall, I'm happy to push a few examples I wrote in Python, but without an API Key it will be useless.

**Comment by polo-mint-driller** [comment]
Script published
